"""init

Revision ID: ce847e75052b
Revises:
Create Date: 2020-06-15 22:12:16.732587

"""
import sqlalchemy as sa
from alembic import op
from app.db.base_class import Enum

# revision identifiers, used by Alembic.
from app.types import MeetingStatus

revision = 'ce847e75052b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'employee',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'file',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('filename', sa.String(), nullable=True),
        sa.Column('checksum', sa.String(), nullable=True),
        sa.Column('length', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'employee_images',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('employee_id', sa.Integer(), nullable=True),
        sa.Column('image_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['image_id'], ['file.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_employee_images_employee_id'), 'employee_images', ['employee_id'], unique=False
    )
    op.create_table(
        'meeting',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('host_id', sa.Integer(), nullable=True),
        sa.Column('status', Enum(MeetingStatus, name="meeting_status"), nullable=False),
        sa.Column('beginAt', sa.DateTime(timezone=True), nullable=False),
        sa.Column('endAt', sa.DateTime(timezone=True), nullable=False),
        sa.Column('location', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['host_id'], ['employee.id'],),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_index(op.f('ix_meeting_host_id'), 'meeting', ['host_id'], unique=False)
    op.create_table(
        'meeting_participant',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('meeting_id', sa.Integer(), nullable=True),
        sa.Column('employee_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_meeting_participant_meeting_id'),
        'meeting_participant',
        ['meeting_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_participant_meeting_id'), table_name='meeting_participant')
    op.drop_table('meeting_participant')
    op.drop_index(op.f('ix_meeting_host_id'), table_name='meeting')
    op.drop_table('meeting')
    op.drop_index(op.f('ix_employee_images_employee_id'), table_name='employee_images')
    op.drop_table('employee_images')
    op.drop_table('file')
    op.drop_table('employee')
    op.exxcute('drop type meeting_status')
    # ### end Alembic commands ###
